#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "interp.h"
static double get(Env*e,const char*s){if(!s||!s[0])return 0;char*ep;double v=strtod(s,&ep);if(ep!=s&&*ep=='\0')return v;for(int i=0;i<e->count;i++)if(!strcmp(e->vars[i].name,s))return e->vars[i].value;if(e->count<MAX_VARS){strcpy(e->vars[e->count].name,s);e->vars[e->count].value=0;e->vars[e->count].used=1;e->count++;}return 0;}
static void setv(Env*e,const char*s,double v){for(int i=0;i<e->count;i++)if(!strcmp(e->vars[i].name,s)){e->vars[i].value=v;e->vars[i].used=1;return;}if(e->count<MAX_VARS){strcpy(e->vars[e->count].name,s);e->vars[e->count].value=v;e->vars[e->count].used=1;e->count++;}}
static int label(const Quad*q,int n,const char*s){for(int i=0;i<n;i++)if(!strcmp(q[i].op,"label")&&!strcmp(q[i].result,s))return i;return -1;}
static int rel(const char*op,double a,double b){if(!strcmp(op,"<"))return a<b;if(!strcmp(op,">"))return a>b;if(!strcmp(op,"<="))return a<=b;if(!strcmp(op,">="))return a>=b;if(!strcmp(op,"=="))return a==b;if(!strcmp(op,"!="))return a!=b;return 0;}
int interpret(const Quad*q,int n,Env*e){int pc=0,steps=0;while(pc<n&&steps++<100000){const Quad*x=&q[pc];if(!strcmp(x->op,"label")){pc++;continue;}if(!strcmp(x->op,"goto")){int t=label(q,n,x->result);if(t<0)return 0;pc=t;continue;}if(!strcmp(x->op,"if")){/* TAC condition is either a relational temp encoded as a value or direct value. */double v=get(e,x->arg1);if(v!=0){int t=label(q,n,x->result);if(t<0)return 0;pc=t;}else pc++;continue;}if(!strcmp(x->op,"=")){setv(e,x->result,get(e,x->arg1));pc++;continue;}double a=get(e,x->arg1),b=get(e,x->arg2),v=0;if(!strcmp(x->op,"+"))v=a+b;else if(!strcmp(x->op,"-"))v=a-b;else if(!strcmp(x->op,"*"))v=a*b;else if(!strcmp(x->op,"/")){if(b==0)return 0;v=a/b;}else if(!strcmp(x->op,"<<"))v=(long long)a<<((int)b);else if(!strcmp(x->op,">>"))v=((long long)a>>((int)b));else if(!strcmp(x->op,"<")||!strcmp(x->op,">")||!strcmp(x->op,"<=")||!strcmp(x->op,">=")||!strcmp(x->op,"==")||!strcmp(x->op,"!="))v=rel(x->op,a,b);else return 0;setv(e,x->result,v);pc++;}return steps<100000;}
static int istemp(const char*s){return s[0]=='t'&&s[1]>='0'&&s[1]<='9';}
int environments_equal(const Env*a,const Env*b){for(int i=0;i<a->count;i++){if(!a->vars[i].used||istemp(a->vars[i].name))continue;double av=a->vars[i].value,bv=get((Env*)b,a->vars[i].name);if(av!=bv)return 0;}for(int i=0;i<b->count;i++){if(!b->vars[i].used||istemp(b->vars[i].name))continue;double av=get((Env*)a,b->vars[i].name);if(av!=b->vars[i].value)return 0;}return 1;}
void dump_env(const Env*e){printf("{");for(int i=0;i<e->count;i++)if(e->vars[i].used)printf(" %s=%.6g",e->vars[i].name,e->vars[i].value);printf(" }\n");}
